@startuml
'https://plantuml.com/class-diagram

'use case interfaces
interface EnhanceNoteDataAccessInterface {
    +enhanceNote(): str
}
interface GenerateStudySheetDataAccessInterface {
    +generateStudySheet(): str
}

'interactors
class EnhanceNoteInteractor
EnhanceNoteInteractor -> EnhanceNoteDataAccessInterface
EnhanceNoteInteractor -> GenerateNoteEnhanceQuery

class GenerateStudySheetInteractor
GenerateStudySheetInteractor -> GenerateStudySheetDataAccessInterface

'entities
class GenerateNoteEnhanceQuery

'data access objects
class OpenAIDataAccessObject extends EnhanceNoteDataAccessInterface, GenerateStudySheetDataAccessInterface

class test1
class test2
test1 -> OpenAIDataAccessObject


@enduml